### ISSUE TITLE
Server at medivia.org:7171 doesn't reply

### ISSUE THREAD

**Issue by eserte** [athreef/Net-OTServ#3]
t/medivia.t started to fail since some days (see http://fast-matrix.cpantesters.org/?dist=Net-OTServ%200.003;reports=1#sl=7,1 for a time-sorted list of reports):
```
Server at medivia.org:7171 doesn't reply. at t/medivia.t line 12.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 1.
t/medivia.t ............ 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 1 subtests passed 
```

**Comment by a3f** [comment]
I am now using [Test::TCP](search.cpan.org/perldoc?Test::TCP) to fork a server locally to test against (88263608c5b2e238603a9882ea9fb37bcc7a071d). Thanks for your report.
